http://scikit-learn.org/stable/modules/neighbors.html<br>
http://scikit-learn.org/stable/auto_examples/neighbors/plot_classification.html#example-neighbors-plot-classification-py<br>
http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.KFold.html<br>

http://scikit-learn.org/stable/modules/classes.html#module-sklearn.neighbors<br>

https://github.com/scikit-learn/scikit-learn/blob/51a765a/sklearn/neighbors/classification.py#L23<br>

In [1]:
%matplotlib inline

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn import neighbors, datasets
import numpy as np

# Load data

In [87]:
df_train = pd.read_csv('../data/train_step1_dummied.csv')
df_target = pd.read_csv('../data/train_step1_target.csv')
df_test = pd.read_csv('../data/test_step1_dummied.csv')

In [88]:
print(df_train.shape, ", ", df_test.shape, ", ", df_target.shape)

(97979, 137) ,  (20746, 102) ,  (97979, 2)


In [89]:
df_train

Unnamed: 0  date_account_created  timestamp_first_active       age  \
0               0              0.309756                0.000000  0.018381   
1               1              0.164024                0.009240  0.027322   
2               2              0.428049                0.086098  0.020368   
3               3              0.000000                0.119789  0.022355   
4               4              0.000610                0.120725  0.022851   
5               5              0.001220                0.120846  0.024342   
6               6              0.001220                0.121271  0.017387   
7               7              0.001829                0.121558  0.017884   
8               8              0.003049                0.122573  0.017387   
9               9              0.003049                0.122903  0.015897   
10             10              0.004878                0.124074  0.013910   
11             11              0.004878                0.124544  0.014406   
12             12              0.005488                0.125102  0.019374   
13             13              0.006098                0.125417  0.012419   
14             14              0.006098                0.125591  0.015400   
15             15              0.007927                0.126861  0.028813   
16             16              0.007927                0.127230  0.014903   
17             17              0.007927                0.127251  0.014406   
18             18              0.008537                0.127621  0.016890   
19             19              0.008537                0.127759  0.012419   
20             20              0.010366                0.128912  0.014406   
21             21              0.012805                0.131475  0.021361   
22             22              0.014634                0.132640  0.013413   
23             23              0.015244                0.133241  0.025832   
24             24              0.015244                0.133689  0.025335   
25             25              0.016463                0.134456  0.018877   
26             26              0.017073                0.134888  0.016890   
27             27              0.017073                0.135140  0.019374   
28             28              0.018902                0.136583  0.014903   
29             29              0.018902                0.136889  0.027819   
...           ...                   ...                     ...       ...   
97949       97949              1.000000                0.999948  0.015897   
97950       97950              1.000000                0.999948  0.016890   
97951       97951              1.000000                0.999951  0.010432   
97952       97952              1.000000                0.999952  0.018381   
97953       97953              1.000000                0.999954  0.011923   
97954       97954              1.000000                0.999955  0.012916   
97955       97955              1.000000                0.999956  0.019871   
97956       97956              1.000000                0.999957  0.013910   
97957       97957              1.000000                0.999957  0.031793   
97958       97958              1.000000                0.999958  0.018381   
97959       97959              1.000000                0.999961  0.010432   
97960       97960              1.000000                0.999962  0.018877   
97961       97961              1.000000                0.999965  0.014406   
97962       97962              1.000000                0.999965  0.014406   
97963       97963              1.000000                0.999968  0.012419   
97964       97964              1.000000                0.999972  0.015400   
97965       97965              1.000000                0.999972  0.012916   
97966       97966              1.000000                0.999974  0.009935   
97967       97967              1.000000                0.999974  0.013413   
97968       97968              1.000000                0.999976  0.024342   
979

In [90]:
df_target

Unnamed: 0 country_destination
0               0                 NDF
1               1                  US
2               2               other
3               3                  US
4               4                  US
5               5                  US
6               6                  US
7               7                 NDF
8               8                 NDF
9               9                  CA
10             10                  FR
11             11                  US
12             12                 NDF
13             13                  FR
14             14                  US
15             15                 NDF
16             16                  US
17             17                 NDF
18             18                 NDF
19             19                 NDF
20             20                  US
21             21                  US
22             22                 NDF
23             23                 NDF
24             24                  US
25             25                 NDF
26             26                  CA
27             27                 NDF
28             28                 NDF
29             29                  FR
...           ...                 ...
97949       97949                  US
97950       97950                 NDF
97951       97951                 NDF
97952       97952                 NDF
97953       97953                 NDF
97954       97954                  US
97955       97955                  GB
97956       97956                 NDF
97957       97957                 NDF
97958       97958                  US
97959       97959                  US
97960       97960                  US
97961       97961                  IT
97962       97962                  AU
97963       97963                 NDF
97964       97964                  US
97965       97965                 NDF
97966       97966                  ES
97967       97967                  US
97968       97968                  US
97969       97969                 NDF
97970       97970                 NDF
97971       97971                 NDF
97972       97972                 NDF
97973       97973                  US
97974       97974                 NDF
97975       97975                  ES
97976       97976                  US
97977       97977                  US
97978       97978                 NDF

[97979 rows x 2 columns]

In [91]:
df_test

Unnamed: 0  date_account_created  timestamp_first_active       age  \
0               0              1.000610                1.000001  0.016890   
1               1              1.000610                1.000003  0.013413   
2               2              1.000610                1.000011  0.011426   
3               3              1.000610                1.000013  0.027322   
4               4              1.000610                1.000015  0.015897   
5               5              1.000610                1.000016  0.014903   
6               6              1.000610                1.000016  0.025832   
7               7              1.000610                1.000018  0.016890   
8               8              1.000610                1.000019  0.016393   
9               9              1.000610                1.000019  0.011923   
10             10              1.000610                1.000021  0.013413   
11             11              1.000610                1.000021  0.015897   
12             12              1.000610                1.000022  0.015400   
13             13              1.000610                1.000024  0.028813   
14             14              1.000610                1.000025  0.012916   
15             15              1.000610                1.000025  0.027819   
16             16              1.000610                1.000025  0.012419   
17             17              1.000610                1.000026  0.017387   
18             18              1.000610                1.000026  0.012916   
19             19              1.000610                1.000027  0.016890   
20             20              1.000610                1.000027  0.010432   
21             21              1.000610                1.000032  0.014406   
22             22              1.000610                1.000035  0.024839   
23             23              1.000610                1.000036  0.011426   
24             24              1.000610                1.000036  0.014406   
25             25              1.000610                1.000041  0.023348   
26             26              1.000610                1.000043  0.018877   
27             27              1.000610                1.000043  0.022851   
28             28              1.000610                1.000044  0.022851   
29             29              1.000610                1.000044  0.013413   
...           ...                   ...                     ...       ...   
20716       20716              1.056098                1.049304  0.014903   
20717       20717              1.056098                1.049306  0.019374   
20718       20718              1.056098                1.049308  0.027819   
20719       20719              1.056098                1.049309  0.014406   
20720       20720              1.056098                1.049312  0.014406   
20721       20721              1.056098                1.049312  0.012916   
20722       20722              1.056098                1.049312  0.012916   
20723       20723              1.056098                1.049314  0.012419   
20724       20724              1.056098                1.049316  0.013910   
20725       20725              1.056098                1.049318  0.019374   
20726       20726              1.056098                1.049320  0.013910   
20727       20727              1.056098                1.049321  0.011923   
20728       20728              1.056098                1.049321  0.014903   
20729       20729              1.056098                1.049322  0.013413   
20730       20730              1.056098                1.049323  0.016890   
20731       20731              1.056098                1.049324  0.025832   
20732       20732              1.056098                1.049326  0.013413   
20733       20733              1.056098                1.049327  0.012916   
20734       20734              1.056098                1.049329  0.017387   
20735       20735              1.056098                1.049330  0.031297   
207

In [92]:
train_rows = df_train.shape[0]
test_rows = df_test.shape[0]

In [93]:
test_train_diff_cols = set(df_test.columns.values) - set(df_train.columns.values)

In [94]:
train_test_diff_cols = set(df_train.columns.values) - set(df_test.columns.values)

# Modify column in Test data

일부 category 정보는 train 혹은 test에만 있는 경우가 있음.

In [95]:
d = pd.DataFrame(0, index=df_test.index, columns=train_test_diff_cols)

In [96]:
d.shape

(20746, 37)

In [97]:
df_test_2 = df_test.join(d)

In [98]:
df_test_2.shape

(20746, 139)

In [99]:
test_train_diff_cols

{'first_browser_UC Browser', 'signup_method_weibo'}

In [100]:
df_test_2 = df_test_2.drop(test_train_diff_cols, axis=1)

In [101]:
df_test_2.shape

(20746, 137)

In [102]:
df_train.shape

(97979, 137)

In [103]:
df_target.shape

(97979, 2)

In [104]:
df_train = df_train.drop(['Unnamed: 0'], axis=1)
df_test_2 = df_test_2.drop(['Unnamed: 0'], axis=1)
df_target = df_target.drop(['Unnamed: 0'], axis=1)

In [44]:
# nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(df_train)

clf = neighbors.KNeighborsClassifier(5, weights='uniform')
clf.fit(df_train, df_target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=5, p=2, weights='uniform')

In [45]:
# distances, indices = nbrs.kneighbors(df_test_2)
clf.predict(df_test_2)

array([[74992, 'NDF'],
       [35438, 'US'],
       [25397, 'NDF'],
       ..., 
       [96328, 'NDF'],
       [86686, 'NDF'],
       [93112, 'US']], dtype=object)

# Cross validation

In [130]:
from sklearn.cross_validation import KFold

len = df_train.shape[0]
kf = KFold(len, n_folds=5)
kf

sklearn.cross_validation.KFold(n=97979, n_folds=5, shuffle=False, random_state=None)

In [131]:
np_train = df_train.as_matrix()
np_target = df_target.as_matrix()

In [132]:
print(np_train[0], np_target[0])

[ 0.3097561   0.          0.01838053  0.          1.          0.          0.
  1.          0.          1.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          1.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          1.          0.          0.          0.          0.
  0.          0.          0.          1.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          1.          0.
  0.          1.          0.          0.          0.          0.          1.

In [133]:
from sklearn.metrics import confusion_matrix

labels = np.unique(np_target)

k_ = 5

cf = None

for train_index, test_index in kf:
    X_train, X_test = np_train[train_index], np_train[test_index]
    y_train, y_test = np_target[train_index], np_target[test_index]
    
    clf = neighbors.KNeighborsClassifier(k_, weights='uniform')
    clf.fit(X_train, y_train)
    
    Z = clf.predict(X_test)
    
    y_test = y_test.T.flatten()
    
    print(labels)
    if cf is None:
        cf = confusion_matrix(Z, y_test, labels=labels)
    else:
        cf = cf + confusion_matrix(Z, y_test, labels=labels)
        
print(cf)

/home/mrthink/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/IPython/kernel/__main__.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/home/mrthink/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/IPython/kernel/__main__.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


['AU' 'CA' 'DE' 'ES' 'FR' 'GB' 'IT' 'NDF' 'NL' 'PT' 'US' 'other']
['AU' 'CA' 'DE' 'ES' 'FR' 'GB' 'IT' 'NDF' 'NL' 'PT' 'US' 'other']
['AU' 'CA' 'DE' 'ES' 'FR' 'GB' 'IT' 'NDF' 'NL' 'PT' 'US' 'other']

/home/mrthink/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/IPython/kernel/__main__.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/home/mrthink/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/IPython/kernel/__main__.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



['AU' 'CA' 'DE' 'ES' 'FR' 'GB' 'IT' 'NDF' 'NL' 'PT' 'US' 'other']
['AU' 'CA' 'DE' 'ES' 'FR' 'GB' 'IT' 'NDF' 'NL' 'PT' 'US' 'other']
[[    0     0     0     1     1     1     3    65     0     0    70    13]
 [    1     4     2     4     8     5     3   144     1     1   184    20]
 [    2     1     2     2    16     4     7    72     1     2   131    19]
 [    5     6     2     5     8     4    10   175     3     0   175    38]
 [    4     5     6    14    49    17    18   295     3     1   347    61]
 [    0     0     1     1     3     1     2    58     0     0    28     8]
 [    1     4     0     5    10     5     6   109     0     0    76    10]
 [  190   454   383   745  1588   786   879 31381   257    69 20615  3267]
 [    0     0     0     0     0     0     0     0     0     0     1     0]
 [    0     0     0     0     0     0     0     0     0     0     0     0]
 [  149   353   288   562  1204   566   646 13196   198    53 15066  2284]
 [    2     6     3     8    17     9     

/home/mrthink/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/IPython/kernel/__main__.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().


In [134]:
print(cf.sum(), cf.diagonal().sum())

97979 46549


In [135]:
print("precision: ", cf.diagonal().sum()/cf.sum()*100)

precision:  47.5091601261
